### ISSUE TITLE
Is it possible to share your dataset?

### ISSUE THREAD

**Issue by YidaYin** [freedomofkeima/MoeFlow#3]
Thanks your work firstly!
I'm currently working on a very similar problem and want to train my network with more data. So I'm just wondering if it is possible to share your training dataset? Thanks!

**Comment by freedomofkeima** [comment]
Hi,

Thanks for your interests! Unfortunately, it's not exactly _legal_ to share those images (~10k images), but you can also scrap it by yourselves in several hours.  The other problem is the dataset size (~20 GB), so I believe it's faster to scrap it from the original source.

The tool that I used was [Nandaka/DanbooruDownloader](https://github.com/Nandaka/DanbooruDownloader). It supports multiple data sources such as  `yande.re` (the one I'm using), `danbooru`, etc.

Thank you.

**Comment by YidaYin** [comment]
Thank you for your reply! 

Actually, I just wrote a crawler to crawl images of popular characters and group them by tag. But I found that the dataset is quite noisy, many of them contain multiple characters. So after you have performed the face detection, did you verify the detected faces manually? Or when choosing images, did you restrict to those images which only has one character appears in their tags?

**Comment by freedomofkeima** [comment]
Hi @ExtraYin ,

Sorry for the late reply (just come back from a 5-day business trip). 

Right, I totally forgot about that part. Yes, from those downloaded images, I separated some of them for manual verification and for the others, I did the manual labeling right after face detection process. In the long run, my plan is to use the resulted model for semi-supervised learning, but at the end, I've never had enough time to do that 😅 

For now, I've uploaded the cleaned data after face detection to [Google Drive](https://drive.google.com/open?id=1ov83AlgEdMkjibrWwBQlJY87s-_eQJ8E). It's around 417 MB and I'll put it there for the next 7 * 24 hours.

By the way, I also wrote a quick summary comparing several computer vision services in a [Medium blog](https://medium.com/@freedomofkeima/flag-17-a-cute-comparison-of-computer-vision-services-781f0f169ceb) with 10 characters / 10 categories. I'm not an expert in computer vision, so those comparison might also be wrong :) 

Thank you.

**Comment by taoky** [comment]
> Hi @ExtraYin ,
> 
> Sorry for the late reply (just come back from a 5-day business trip).
> 
> Right, I totally forgot about that part. Yes, from those downloaded images, I separated some of them for manual verification and for the others, I did the manual labeling right after face detection process. In the long run, my plan is to use the resulted model for semi-supervised learning, but at the end, I've never had enough time to do that 😅
> 
> For now, I've uploaded the cleaned data after face detection to [Google Drive](https://drive.google.com/open?id=1ov83AlgEdMkjibrWwBQlJY87s-_eQJ8E). It's around 417 MB and I'll put it there for the next 7 * 24 hours.
> 
> By the way, I also wrote a quick summary comparing several computer vision services in a [Medium blog](https://medium.com/@freedomofkeima/flag-17-a-cute-comparison-of-computer-vision-services-781f0f169ceb) with 10 characters / 10 categories. I'm not an expert in computer vision, so those comparison might also be wrong :)
> 
> Thank you.

Sorry to have disturbed you. I'm also trying to classify anime characters, and having a bad time collecting & classifying these images. I tried downloading your dataset on your link to Google Drive, but it seems broken and returns HTTP 404.

Would you please fix that link? Thank you.
